steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nfs-test-client'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-repo/kirby-backend:testing'
      - '--region'
      - 'europe-west1'
      - '--network=deloitte-greenhouse-2024-nfs'
      - '--subnet=deloitte-greenhouse-2024-nfs-subnet'
      - '--add-volume'
      - 'name=volume-data-nfs,type=nfs,location=192.168.200.2:/data/shared'
      - '--add-volume-mount'
      - 'volume=volume-data-nfs,mount-path=/data/persistent_volume'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1'
options:
  logging: CLOUD_LOGGING_ONLY
